#Server
server:
  servlet:
    context-path: /lightmin-client
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lightmin-client
  #ligtmin
  batch:
    job:
      enabled: false
    lightmin:
      server:
        discovery-enabled: true
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        classic:
          server:
            url: http://localhost:50103/lightmin-server
        client:
          publish-job-events: true
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_
    repository:
      jdbc:
        #override the default table names
        job-configuration-table-name: batch_job_configuration
        job-configuration-value-table-name: batch_configuration_value
        job-configuration-parameter-table-name: batch_configuration_parameter
management:
  endpoints:
    web:
      exposure:
        include: "*"
debug: true