#Server
server:
  servlet:
    context-path: /lightmin-client
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lightmin-client
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        classic:
          server:
            url: http://localhost:50103/lightmin-server
        client:
          publish-job-events: true
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_

debug: true