# to define server name
#server:
 # servlet:
  #  context-path: #
spring:
  application:
    name: jobServer
  batch:
    job:
      enabled: false
    lightmin:
      server:
        cluster:
          infinispan:
            repository:
              init-scheduler-configuration-repository: true # default false (1)
              init-scheduler-execution-repository: true # default false (2)